### ISSUE TITLE
Segoe UI font - browser weight issue?

### ISSUE THREAD

**Issue by AaronUXD** [USPTO/designpatterns#22] opened 2014-12-15 18:45 UTC
Chrome only seams to render the 700 weight of Segoe UI, explorer renders them all. Are others having this problem?

![image](https://cloud.githubusercontent.com/assets/9051299/5441693/96cbfa50-8460-11e4-90fe-d7e016f36dbb.png)

**Comment by bmathews** [comment] 2015-01-26 21:07
Closing as a duplicate of #37, since #37 more information.

**Closed by bmathews** 2015-01-26 21:07 UTC
Labels: browser: Chrome, needs: feedback, type: defect
